description: job-testing-flow

target:
  name: aims-sing-a100-wus3 #  # aims-sing-a100-wus3 genai-win-sa #
  workspace_name: Singularity-GenAI-WS-UKSouth # genai-phi-san #
  service: sing

environment:
  image: ys_flashattn2:v4.1
  username: phipretraining
  registry: phipretraining.azurecr.io
  setup:
    - set -e -o xtrace
    - export PATH=/home/$$USER/.local/bin:$$PATH
    - printenv
    - pip install -e .
    # - pip install lm-eval==0.4.7
    # - pip install datasets==3.2.0
    # - pip install transformers==4.47.1
    # - pip install evaluate==0.4.3

storage:
  aimsllmeus2_data:
    storage_account_name: aimsllmeus2
    container_name: data
    mount_dir: /mnt/aimsllmeus2_data

code:
  local_dir: ./

env_defaults:
  uai: /subscriptions/d676d072-7cbf-4197-b2d6-17ecf38370d0/resourceGroups/Singularity-GenAI-GPU-UKSouth/providers/Microsoft.ManagedIdentity/userAssignedIdentities/genai-sing-uai


jobs:
  - name: "phi_mini_inference"
    sku: 1x80G4-A100-IB-NvLink
    process_count_per_node: 1
    sla_tier: Premium
    execution_mode: basic
    priority: high
    identity: managed
    command:
      - set -x
      - export PATH=/home/aiscuser/.local/bin:$$PATH
      - export PATH=$$HOME/.local/bin/:$$PATH
      - echo $${NODE_RANK}
      - printenv
      - pip install zuko
      - pip install scikit-learn
      - 'git clone https://github.com/yelongshen/rlray.git'
      - cd rlray
      - pip install .
      - cd xlmlib
      - torchrun --nproc_per_node 1 --nnodes 1 --node_rank $${NODE_RANK} --master_addr $${MASTER_ADDR} --master_port $${MASTER_PORT} phi_inference.py --pretrained_model /mnt/aimsllmeus2_data/phimodels/
    submit_args:
      env:
        _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/d676d072-7cbf-4197-b2d6-17ecf38370d0/resourceGroups/Singularity-GenAI-GPU-UKSouth/providers/Microsoft.ManagedIdentity/userAssignedIdentities/genai-sing-uai